title: Yiorgos Patsios
description: DevOps Engineer | Data Scientist | Mathematics PhD
show_downloads: false

theme: jekyll-theme-dinky

# Personal info
email: giopatsios@gmail.com
location: Athens, Greece

# Social links
github_username: gamma-pi
linkedin_username: yiorgos-patsios