theme: jekyll-theme-minimal
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

# Site settings
title: Yiorgos Patsios
description: DevOps Engineer | Data Scientist | Mathematics PhD

# Personal info
email: giopatsios@gmail.com
location: Athens, Greece
phone: (+30) 6945921304

# Social links
github_username: gamma-pi
linkedin_username: yiorgos-patsios
google_scholar: yiorgospatsios

# Optional
show_downloads: false
